name: UHC
main: com.leontg77.uhc.Main
version: 1.7.2
author: LeonTG77
description: UHC plugin made for Leons UHC

commands:
  aboard:
    description: Toggle the arena board.
  arena:
    description: Command to join the arena.
    aliases: [a, p]
  ban:
    description: Ban a player.
    aliases: [dq]
  board:
    description: Toggle the pregame board.
  border:
    description: View the border size.
  broadcast:
    description: Broadcast a message to all players online.
    aliases: [bc, bcast]
  butcher:
    description: Kills all hostile mobs.
  config:
    description: Change the config settings.
  clearchat:
    description: Clear the chat.
    aliases: [cc]
  clearinv:
    description: Clear someones inv.
  clearxp:
    description: Clear someones xp.
  edit:
    description: Edit the sign you are looking at.
  end:
    description: End the game and reset everything.
  feed:
    description: Feed someone.
  gamemode:
    description: Change your gamemode.
    aliases: [gm]
  giveall:
    description: Give everyone online an item.
  heal:
    description: Heal someone.
  health:
    description: View a player's health.
    aliases: [h]
  helpop:
    description: If you need help from staff, use this command.
  hof:
    description: View the hall of fame.
    aliases: [halloffame]
  invsee:
    description: Opens the targets inventoty.
  kick:
    description: Kick a player.
  list:
    description: Shows a list of online players.
  matchpost:
    description: Get the link of the match post.
    aliases: [post]
  ms:
    description: Check someones ping to the server
    aliases: [ping]
  msg:
    description: Msg a player something secret.
    aliases: [t, tell, w, whisper, m]
  mute:
    description: Mute a player or the chat.
  near:
    description: Check for nearby players.
  perma:
    description: Enable permaday.
  pm:
    description: Team chat command.
  pvp:
    description: Toggle pvp in a specific world.
  random:
    description: Create random teams.
  rank:
    description: Change someones rank.
  reply:
    description: Reply to your latest msg.
    aliases: [r]
  rules:
    description: View our rules.
  scenario:
    description: Enable and disable scenarios
    aliases: [scen]
  sethealth:
    description: Set the health of a player.
  setmaxhealth:
    description: Set the max health of a player.
  skull:
    description: Spawn a player head.
  spectate:
    description: Change your spectator status.
    aliases: [spec]
  setspawn:
    description: Set the lobby spawn point.
  speed:
    description: Change your fly/walk speed
  spread:
    description: Spread all players and freeze them.
  ac:
    description: StaffChat Command
    aliases: [sc]
  start:
    description: Start command.
  stats:
    description: View your stats.
  team:
    description: Team command, check usage.
    aliases: [party]
  tempban:
    description: Tempban a player.
    aliases: [tban]
  text:
    description: Spawn a floating text.
  timeleft:
    description: Check the time left.
  timer:
    description: Hotbar timer command.
  teamloc:
    description: Tell your location out to your teammates.
    aliases: [tl]
  tps:
    description: Check the server tps and usage.
    aliases: [lag]
  tp:
    description: Makes you able to teleport as a spectator.
  unban:
    description: Unban a player.
  vote:
    description: Start or end a vote.
  whitelist:
    description: Whitelisting command.
    aliases: [wl]
  class:
    description: View your AssaultAndBarrery type.
  listclass:
    description: View who has what AssaultAndBarrery type.
  slavereset:
    description: Reset slavemarket.
  slaveowner:
    description: Manage slave owners.
  startbid:
    description: Start a bid on a player.
  bid:
    description: Bid on a player.
  mt:
    description: Mystery teams command.